### ISSUE TITLE
Out of Date Artifact Registered w/ pip

### ISSUE THREAD

**Issue by dr00b** [yubin-park/hccpy#17]
@yubin-park Awesome work!

I think the patch addressing #9 is not present in version 1.0 artifact registered with pip. Still observing the issue where HCC18 is not overwriting HCC19 due to dx-HCC, 1->many mapping. As an example, E1151 maps to both HCC108 and HCC18.

I'll just clone out the repo for now.

**Comment by yubin-park** [comment]
@dr00b updated pip version with the latest master. Thanks!
