### ISSUE TITLE
HHSHCCEngine

### ISSUE THREAD

**Issue by tkihlstadius** [yubin-park/hccpy#18]
How do you add the parameter enroll months to the HHSHCCEngine? When I do it like so: age=45, sex="M", enroll_months = 2, I get an error. Unexpected keyword argument 'enroll_months.'
My code works if I take out the enroll_months = 2.
rp = hs.profile(["C4359"], ["98942"], age=45, sex="M", enroll_months = 2)
print(json.dumps(rp, indent=2))

**Comment by mwalker14** [comment]
hi @tkihlstadius that one is on me.  i wrote an update to add the enrolled months as a parameter but when i submitted the fork i somehow left out a piece of the code in the module that populates the risk_dict.  i have a pull request that fixes the bug that @yubin-park needs to qa and merge into the master.

**Comment by tkihlstadius** [comment]
Hi, thanks for the update. When will the code be ready to use for the HHSHCC engine? Will you post sample code to clarify formatting of the parameters? 
Thank you for your help on this.
Tammy

**Comment by tkihlstadius** [comment]
Hi, just checking in on when the code will be updated for the HHSHCC engine? Thanks!

**Comment by tkihlstadius** [comment]
Hi, just checking in on when the code will be updated for the HHSHCC engine? Thanks!

**Comment by yubin-park** [comment]
@tkihlstadius @mwalker14 I just merged the pull request @mwalker14 mentioned. Sorry for the super late response on this. My apologies. Thanks, all!
