### ISSUE TITLE
Understanding Result Question

### ISSUE THREAD

**Issue by Lijo-CheeranJoseph** [yubin-park/hccpy#20]
I am trying to learn this library. Consider following:
rp9 = he.profile(["E11.59", "Z79.4", "I73.9", "Z89.412"], age=65, sex = "F", elig = "CFA")
print(json.dumps(rp9, indent=2))

In the "details" section of the result, there is "CFA_F65_69". Where can I see details of this to see what it means?
In the "hcc_lst" it has "D3". What does "D3" means? 
Why is "CNA_D3" value 0.0?

**Comment by mwalker14** [comment]
@Lijo-CheeranJoseph:

In the "details" section of the result, there is "CFA_F65_69". Where can I see details of this to see what it means?  **that is the demographic age/sex score.  this patient is a 65 y/o female.  demographic scores are based on the age group and gender**

In the "hcc_lst" it has "D3". What does "D3" means?  **the patient has 3 diseases mapped to HCC**

Why is "CNA_D3" value 0.0?  **not every code has a risk value.  in this model, the minimum to start adding more risk is 4**

Cheers, hope that helps.

**Comment by Lijo-CheeranJoseph** [comment]
Thanks for the clarification @mwalker14

**Comment by yubin-park** [comment]
Closing the issue as @mwalker14 answered it. Thanks, @mwalker14!
