### ISSUE TITLE
ICD 10 Diagnosis Codes that has HCC Score

### ISSUE THREAD

**Issue by Lijo-CheeranJoseph** [yubin-park/hccpy#21]
Hi,
Is there an CMS resource that specified all ICD 10 codes and the corresponding HCC number?  I have seen a CMS file that has diagnosis description and HCC number mapping - but not with ICD 10 code.

**Comment by dr00b** [comment]
Hi Joseph,
https://www.cms.gov/Medicare/Health-Plans/MedicareAdvtgSpecRateStats/Risk-Adjustors
CMS posts the mappings in a nice Excel spreadsheet, along with the SAS code etc. on their website.

**Comment by yubin-park** [comment]
Closing the issue as @dr00b answered the question. Thanks!
