### ISSUE TITLE
Help with HHSHCC engine

### ISSUE THREAD

**Issue by tkihlstadius** [yubin-park/hccpy#22]
Hi, just checking in on when the code will be updated for the HHSHCC engine? Thanks!

**Comment by yubin-park** [comment]
@tkihlstadius sorry for the late reply on this. Will prioritize updating this. Please check in again a couple of weeks.

**Comment by tkihlstadius** [comment]
Thank you!

**Comment by yubin-park** [comment]
https://github.com/yubin-park/hccpy/issues/18#issue-943559349 related issue -> closed. Thanks!
