### ISSUE TITLE
Error in V0519F3P.get_risk_dct() function

### ISSUE THREAD

**Issue by sreesatwik** [yubin-park/hccpy#28]
Hi,

There seems to be an inconsistency in function definition here 
https://github.com/yubin-park/hccpy/blob/f452f13c1450ba007c7e404764b2d535b7cd8caf/hccpy/_V0519F3P.py#L2

and function call here
https://github.com/yubin-park/hccpy/blob/f452f13c1450ba007c7e404764b2d535b7cd8caf/hccpy/hhshcc.py#L97

Notice the missing enroll_dur parameter. This is causing a TypeError.
`TypeError: get_risk_dct() missing 1 required positional argument: 'plate'`

Thank you.

**Comment by proinsias** [comment]
@yubin-park – do you have a new ETA for this fix?

**Comment by yubin-park** [comment]
@proinsias @sreesatwik sorry about that. Somehow the issue was mysteriously closed. I will get you all updated with the fix soon. I will close the issue after the fix is completed. Please keep the issue open. Best,

**Comment by yubin-park** [comment]
@proinsias @sreesatwik if you pull the master branch, the code should be fixed. Thanks a lot!

**Comment by proinsias** [comment]
Thanks @yubin-park!!! – do you have an ETA for your next release that would contain the fix?

**Comment by yubin-park** [comment]
@proinsias sorry - didn't see the message as the issue was already closed. 
https://pypi.org/project/hccpy/
Please see the new release and let me know if you still face problems. Thanks!
