### ISSUE TITLE
Implementation of risk adjustment eligible claims

### ISSUE THREAD

**Issue by ThomasC0124** [yubin-park/hccpy#3]
For diagnosis codes to be considered in MA risk models, one must first determine if the source medical claims are **risk adjustment eligible**, by checking their claim types (inpatient, outpatient or professional), bill type codes and whether they contain specific CPT/HCPCS codes.

For more details about the procedure codes, please visit the following website: https://www.cms.gov/Medicare/Health-Plans/MedicareAdvtgSpecRateStats/Risk-Adjustors-Items/CPT-HCPCS.html?DLPage=1&DLEntries=10&DLSort=0&DLSortDir=descending

**Comment by yubin-park** [comment]
Added a module that addresses this issue.
