### ISSUE TITLE
Getting error "name 'hcpcs' is not defined" for hhshcc 

### ISSUE THREAD

**Issue by cbio-bvilla** [yubin-park/hccpy#51]
I'm getting a NameError in hhshcc.py line 99

NameError: name 'hcpcs' is not defined

```
99         cc_dct.update({hcpcs:self.hcpcs2rxc[pr] for pr in pr_lst
100                         if pr in self.hcpcs2rxc})
```

**Comment by ronnie-canopy** [comment]
I also saw this. I am not using this part of the code, but I suspect changing "hcpcs" to "pr" will solve the problem. It looks like a switch from "pr" for "procedure code" to "hcpcs" happened, where both can reference the same concept.

**Comment by yubin-park** [comment]
@cbio-bvilla @ronnie-canopy the latest master branch fixed the bug. Thanks for reporting!
