### ISSUE TITLE
hccpy V28 - Test Case Development

### ISSUE THREAD

**Issue by dr00b** [yubin-park/hccpy#56]
Greetings hccpy community! We do intend to implement the HCC V28 model and will begin work as soon as the SAS model is released. In the meantime, let's collaborate on a high quality test-set using the documentation we have ([see pg 183](https://www.cms.gov/files/document/2024-announcement-pdf.pdf))

In order to contribute, take the following steps:
1. Propose a test case via a comment on this issue. Make sure to review what's already been proposed.
3. Branch off `v28-test-case`.
4. Implement a unittest under `tests/hcc_v28_tests.py`. See `tests/hcc_tests.py`, "test_risk_scores" method for examples.
5. PR back into `v28-test-case`, assigning an independent reviewer (me!)

**Comment by yubin-park** [comment]
@dr00b @kevinbuchanjr please check the latest master branch. I pushed the V28 version. THanks!
