### ISSUE TITLE
Missing code for heart interaction patch

### ISSUE THREAD

**Issue by ronnie-canopy** [yubin-park/hccpy#58]
Lines 448 to 450 of V2823T2M.txt contain the condition:

            %*heart interaction patch;
            IF CC223 = 1 AND MAX(CC221, CC222, CC224, CC225, CC226) = 0                                                                                                                                          
            THEN CC223 = 0;  

Should these lines also appear in the corresponding Python file?
I do not see them present.

**Comment by yubin-park** [comment]
@ronnie-canopy really good catch! thanks. I will patch it now

**Comment by yubin-park** [comment]
@ronnie-canopy I just added this block at line 84 in hcc.py
```
        if self.version == "28": # V28 weird patch for heart
            if (cc_cnt["HCC223"] > 0 and 
                (cc_cnt["HCC221"] + cc_cnt["HCC222"] + 
                cc_cnt["HCC224"] + cc_cnt["HCC225"] + 
                cc_cnt["HCC226"]) == 0):
                cc_cnt["HCC223"] = 0
```

**Comment by Short-N** [comment]
Interesting that the Advance Notice copy only includes 224, 225, and 226 in the criteria.
