### ISSUE TITLE
V24

### ISSUE THREAD

**Issue by Rongrs** [yubin-park/hccpy#6]
v24 is not published on `nber` and probably wouldn't be published
what is the process that needs to happen in order to create the coefficients file from the official CMS files?
Thanks for the great library :-)

**Comment by cwkoenigs** [comment]
I extracted it into an xls from the SAS model in the CMS website. I do not have access to SAS so I used stat transfer.

**Comment by yubin-park** [comment]
@Rongrs good point, and yes, I was a bit stuck on how to get the coefficients.
@cwkoenigs would appreciate it if you could share the link to the SAS model or the extracted coefficients. Will update the package with those. 
Thanks!

**Comment by cwkoenigs** [comment]
@yubin-park  Thank you for all of your hard work! 

[V24hcccoefn.zip](https://github.com/yubin-park/hccpy/files/5063470/V24hcccoefn.zip)

https://www.cms.gov/Medicare/Health-Plans/MedicareAdvtgSpecRateStats/Risk-Adjustors-Items/Risk2020

I have updated the model to include v12 (2015)/ICD 9  for RADV purposes, updated to include v24, and added 2020 to v22. 

I would happily send you over my work. I am fairly new to python, so I was/am a bit hesitant to upload to straight to git.

**Comment by bdsvc-github** [comment]
Deployment starting to ephemeral!

**Comment by bdsvc-github** [comment]
Deployed to ephemeral!
