### ISSUE TITLE
Converting from raw RAF to pricing (normalized RAF)

### ISSUE THREAD

**Issue by ronnie-canopy** [yubin-park/hccpy#63]
See the attached file for a dictionary with some historic MA normalization factors and the implementation of said factors - in the profile method.

The MA coding pattern has not yet changed over time, so it is a simple constant for now.
However, CMS can change this value whenever they deem it appropriate.
The current value of 5.9% is the minimum value permitted.

Despite the build-out of some code for ESRD in that attached file, this portion is very much a work in progress.

[hcc.py.txt](https://github.com/yubin-park/hccpy/files/11455862/hcc.py.txt)

**Comment by yubin-park** [comment]
@ronnie-canopy  thanks so much. It was extremely helpful. I modified the script for backward compatibility and extensibility. Please check the latest master branch. Best,
