### ISSUE TITLE
gRespDepandArre_gCopd mismatch in V23hcccoefn.csv and _V2318P1M.py

### ISSUE THREAD

**Issue by cwkoenigs** [yubin-park/hccpy#8]
V23hcccoefn.csv has lower case R's for this interaction (grespDepandArre_gCopd) and thus interactions for gRespDepandArre_gCopd are not working. Either updating V23hcccoefn.csv to match _V2318P1M.py or updating _V2318P1M.py to match V23hcccoefn.csv will work. There are six instances.

**Comment by yubin-park** [comment]
Thanks, @cwkoenigs I took your first suggestion - fixing V23hcccoefn.csv to match the other. The latest master branch should reflect the change. Best,
