### ISSUE TITLE
HCC's being suppressed 

### ISSUE THREAD

**Issue by cwkoenigs** [yubin-park/hccpy#9]
There are several dx codes that map to multiple HCCs. For example, in V24, E1151 should map to HCC18 and HCC108. However, it only maps to 108. I believe this occurs when the read_dx2cc is being called from utils.py it creates a dict that can only match the dx code to one hcc.

**Comment by yubin-park** [comment]
@cwkoenigs my mistake to ignore the one (dx) to many (hccs) relationships. Will patch it this or next week. Would be helpful if you could give me more test cases. Thanks so much!

**Comment by cwkoenigs** [comment]
@yubin-park Thank you so much! 
Attached is a .txt file with a bunch. 

[one2manytest.txt](https://github.com/yubin-park/hccpy/files/5583249/one2manytest.txt)

**Comment by yubin-park** [comment]
@cwkoenigs Please check the latest master branch. I address the one to many mappings. Thanks for the help!

**Comment by cwkoenigs** [comment]
@yubin-park thanks! Everything looks great.
